language: node_js
node_js:
- '0.11'
- '0.10'
- '0.12'
- "io.js"
script:
- make test-cov
- cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js > /dev/null 2>&1
deploy:
  provider: npm
  email: eirik@morland.no
  api_key:
    secure: WsqApO/9s1m4yX9x9Cie1QOOe0h2c9ZMwkaaWbRuvgFzyDP8KPxC+t90JxNjYa1yp0zbNSf3MsklB+8UPMLsIrRGgttYmQeTPnTyyufGJoyMkYO9lUa4k676NlGEdZ49Jrfubm0s/krOoghNKsfkSzteab7znM8FWmEsMCujuv0=
  on:
    tags: true
    repo: eiriksm/readmeify
sudo: false
